# Generated by Django 3.1.6 on 2021-03-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0008_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
