# Generated by Django 3.1.6 on 2021-04-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0011_auto_20210415_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='fork_of',
            field=models.IntegerField(default=-1),
        ),
    ]
