# Generated by Django 3.1.6 on 2021-03-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0006_auto_20210308_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
