# Generated by Django 3.1.6 on 2021-04-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0010_userprofile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='apple_music_id',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='item',
            name='manual_link',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='item',
            name='spotify_id',
            field=models.CharField(default='', max_length=64),
        ),
    ]
